# Generated by Django 3.2.25 on 2024-03-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='first_name',
        ),
    ]
