# Generated by Django 3.2.25 on 2024-03-29 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_rename_user_name_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sent_request', to=settings.AUTH_USER_MODEL)),
                ('request_sent_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_recieved_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('request_sent_by', 'request_sent_to')},
            },
        ),
    ]
